# Generated by Django 4.0.1 on 2023-05-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedfood',
            options={'verbose_name': 'ordered food', 'verbose_name_plural': 'ordered food'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
