# Generated by Django 4.0.1 on 2023-05-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderedfood_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfood',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
    ]
